import {
  User as UserIcon,
  Mail,
  Shield,
  FileText,
  Lock,
  Clock,
  Calendar,
  CalendarClock,
  Hash,
  UserPlus,
} from "lucide-react";

export const USER_FIELDS = [
  {
    id: "id",
    label: "ID",
    required: false,
    sortable: true,
    center: true,
    icon: Hash,
  },
  {
    id: "fullName",
    label: "Full Name",
    required: true,
    sortable: true,
    center: false,
    icon: UserIcon,
  },
  {
    id: "email",
    label: "Email",
    required: false,
    sortable: true,
    center: false,
    icon: Mail,
  },
  {
    id: "role",
    label: "Role",
    required: false,
    sortable: true,
    center: false,
    icon: Shield,
  },
  {
    id: "description",
    label: "Description",
    required: false,
    sortable: true,
    center: false,
    icon: FileText,
  },
  {
    id: "addedBy",
    label: "Added By",
    required: false,
    sortable: true,
    center: false,
    icon: UserPlus,
  },
  {
    id: "isLocked",
    label: "Locked",
    required: false,
    sortable: true,
    center: true,
    icon: Lock,
  },
  {
    id: "lastLogin",
    label: "Last Login",
    required: false,
    sortable: true,
    center: true,
    icon: Clock,
  },
  {
    id: "createdAt",
    label: "Created At",
    required: false,
    sortable: true,
    center: true,
    icon: Calendar,
  },
  {
    id: "updatedAt",
    label: "Updated At",
    required: false,
    sortable: true,
    center: true,
    icon: CalendarClock,
  },
] as const;

// Default visible columns
export const DEFAULT_USER_COLUMNS = [
  "fullName",
  "email",
  "role",
  "addedBy",
  "lastLogin",
] as const;
